const http = require('http');
const path = require('path');
const crypto = require('crypto');
const express = require('express');
const { WebSocketServer } = require('ws');
const app = express();
app.use(express.json()); app.use(express.static(path.join(__dirname,'public'))); app.get('/health',(_,res)=>res.json({ok:true}));
const server=http.createServer(app), wss=new WebSocketServer({server,path:'/ws'}), rooms=new Map();
const names=['A','B','C','D','E','F','G','H','J','K','M','N','P','Q','R','S','T','V','W','X'], STEP_SECONDS=30;
function code(){let s='';do{s='';for(let i=0;i<6;i++)s+=names[Math.floor(Math.random()*names.length)];}while(rooms.has(s));return s}
function id(){return crypto.randomBytes(8).toString('hex')}
function roleCounts(n){if(n<4)return{mafia:1,doctor:0,detective:0};return{mafia:Math.max(1,Math.floor(n/4)),doctor:n>=6?1:0,detective:n>=5?1:0}}
function makeRoles(n){const c=roleCounts(n),r=[];for(let i=0;i<c.mafia;i++)r.push('mafia');if(c.doctor)r.push('doctor');if(c.detective)r.push('detective');while(r.length<n)r.push('town');return r.sort(()=>Math.random()-.5)}
function publicState(room){const nominationVotes={};for(const id of Object.values(room.nominationVotes||{}))nominationVotes[id]=(nominationVotes[id]||0)+1;return{code:room.code,phase:room.phase,day:room.day,night:room.night,deadline:room.deadline||null,players:[...room.players.values()].map(p=>({id:p.id,name:p.name,alive:p.alive,will:p.will||'',avatar:p.avatar||''})),nominationVotes,nominee:room.nominee||null,trialVotes:room.trialVotes||{},winner:room.winner||null}}
function send(ws,msg){if(ws?.readyState===1)ws.send(JSON.stringify(msg))}function broadcast(room,msg){for(const p of room.players.values())send(p.ws,msg);send(room.host,msg)}function push(room){broadcast(room,{type:'state',state:publicState(room)})}
function privateRole(room,p){send(p.ws,{type:'role',role:p.role,room:room.code})}
function clearTimer(room){if(room.timer)clearTimeout(room.timer);room.timer=null;room.deadline=null}
function setStepTimer(room,seconds,fn){clearTimer(room);room.deadline=Date.now()+seconds*1000;room.timer=setTimeout(()=>{room.timer=null;room.deadline=null;fn()},seconds*1000);push(room)}
function checkWin(room){const alive=[...room.players.values()].filter(p=>p.alive),m=alive.filter(p=>p.role==='mafia').length,non=alive.length-m;if(m===0)room.winner='town';else if(m>=non)room.winner='mafia';if(room.winner){clearTimer(room);room.phase='gameover';broadcast(room,{type:'announcement',text:`${room.winner==='town'?'Town':'Mafia'} wins!`})}}
function startNight(room){room.phase='night';room.night++;room.actions={kills:null,protect:null,inspect:null};room.nominee=null;room.trialVotes={};room.nominationVotes={};broadcast(room,{type:'narration',text:`Night ${room.night}. Everyone goes to sleep.`});setStepTimer(room,STEP_SECONDS,()=>resolveNight(room))}
function resolveNight(room){if(room.phase!=='night')return;clearTimer(room);const target=room.actions.kills,prot=room.actions.protect;if(target&&target!==prot){const v=room.players.get(target);if(v)v.alive=false;room.lastDeath=v?.id||null}else room.lastDeath=null;room.phase='dawn';if(room.lastDeath){const v=room.players.get(room.lastDeath);broadcast(room,{type:'dawn',victim:{name:v.name,role:v.role,will:v.will||''}})}else broadcast(room,{type:'dawn',victim:null});checkWin(room);if(!room.winner)setStepTimer(room,STEP_SECONDS,()=>startDiscussion(room));else push(room)}
function startDiscussion(room){if(room.phase==='gameover')return;room.phase='discussion';room.nominationVotes={};room.nominee=null;broadcast(room,{type:'narration',text:`Day ${room.day}. Meeting begins. Everyone has 30 seconds to nominate a player.`});setStepTimer(room,STEP_SECONDS,()=>resolveNomination(room))}
function resolveNomination(room){if(room.phase!=='discussion')return;clearTimer(room);const counts={};for(const target of Object.values(room.nominationVotes||{}))counts[target]=(counts[target]||0)+1;const alive=[...room.players.values()].filter(p=>p.alive);let max=0,leaders=[];alive.forEach(p=>{const n=counts[p.id]||0;if(n>max){max=n;leaders=[p]}else if(n===max&&n>0)leaders.push(p)});const n=leaders.length?leaders[Math.floor(Math.random()*leaders.length)]:alive[Math.floor(Math.random()*alive.length)];room.nominee=n?.id||null;room.phase='trial';room.trialVotes={};broadcast(room,{type:'nominated',id:n?.id,name:n?.name,automatic:true,votes:max});if(n)setStepTimer(room,STEP_SECONDS,()=>trialResult(room))}
function startGame(room){const ps=[...room.players.values()],roles=makeRoles(ps.length);ps.forEach((p,i)=>{p.role=roles[i];p.alive=true});room.phase='role';room.day=1;room.night=0;room.winner=null;ps.forEach(p=>privateRole(room,p));broadcast(room,{type:'narration',text:'Roles have been dealt. Check your phone privately.'});setStepTimer(room,STEP_SECONDS,()=>startNight(room))}
function trialResult(room){if(room.phase!=='trial')return;clearTimer(room);const votes=Object.values(room.trialVotes||{}),g=votes.filter(v=>v==='guilty').length,i=votes.filter(v=>v==='innocent').length,n=room.players.get(room.nominee);if(g>i){if(n)n.alive=false;broadcast(room,{type:'trialResult',result:'guilty',name:n?.name})}else broadcast(room,{type:'trialResult',result:'innocent',name:n?.name});checkWin(room);if(!room.winner){room.day++;startNight(room)}else push(room)}
wss.on('connection',ws=>{ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}
if(m.type==='create'){const room={code:code(),host:ws,players:new Map(),phase:'lobby',day:0,night:0,deadline:null,timer:null};rooms.set(room.code,room);ws.room=room.code;send(ws,{type:'created',code:room.code});push(room);return}
if(m.type==='join'){const room=rooms.get(String(m.code||'').toUpperCase());if(!room)return send(ws,{type:'error',message:'Room not found'});if(room.phase!=='lobby')return send(ws,{type:'error',message:'Game already started'});const p={id:id(),name:String(m.name||'Player').slice(0,24),will:String(m.will||'').slice(0,500),avatar:String(m.avatar||'').slice(0,500000),alive:true,role:null,ws};room.players.set(p.id,p);ws.playerId=p.id;ws.room=room.code;send(ws,{type:'joined',id:p.id,code:room.code});push(room);return}
const room=rooms.get(ws.room);if(!room)return;
if(m.type==='start'&&ws===room.host){if(room.players.size<4)return send(ws,{type:'error',message:`Need at least 4 players. Currently ${room.players.size}.`});startGame(room)}
if(m.type==='will'){const p=room.players.get(ws.playerId);if(p)p.will=String(m.will||'').slice(0,500);push(room)}
if(m.type==='avatar'){const p=room.players.get(ws.playerId);if(p)p.avatar=String(m.avatar||'').slice(0,500000);push(room)}
if(m.type==='nightAction'){const p=room.players.get(ws.playerId);if(!p?.alive||room.phase!=='night')return;const t=room.players.get(m.target);if(!t?.alive)return;if(p.role==='mafia')room.actions.kills=m.target;if(p.role==='doctor')room.actions.protect=m.target;if(p.role==='detective'){room.actions.inspect=m.target;send(ws,{type:'investigation',name:t.name,isMafia:t.role==='mafia'})}const alive=[...room.players.values()].filter(x=>x.alive),md=alive.filter(x=>x.role==='mafia').every(x=>room.actions.kills),doc=[...room.players.values()].find(x=>x.role==='doctor'),det=[...room.players.values()].find(x=>x.role==='detective');if(md&&(!doc||room.actions.protect)&&(!det||room.actions.inspect))resolveNight(room)}
if(m.type==='nominate'&&room.phase==='discussion'){const p=room.players.get(ws.playerId),n=room.players.get(m.target);if(p?.alive&&n?.alive&&p.id!==n.id){room.nominationVotes[p.id]=n.id;push(room)}}
if(m.type==='trialVote'&&room.phase==='trial'){const p=room.players.get(ws.playerId);if(p?.alive&&['guilty','innocent'].includes(m.vote)){room.trialVotes[p.id]=m.vote;push(room);const alive=[...room.players.values()].filter(x=>x.alive);if(alive.every(x=>room.trialVotes[x.id]))trialResult(room)}}
});ws.on('close',()=>{})});
const PORT=process.env.PORT||10000;server.listen(PORT,'0.0.0.0',()=>console.log(`Mafia server listening on ${PORT}`));
